let load1 = [
	{deptnum: "CHEM 125", name: "Struct Chem & Equilib Lab"},
	{deptnum: "CHEM 125", name: "Struct Chem & Equilib"},
	{deptnum: "CHEM 126", name: "Chemical Reactions"},
	{deptnum: "CHEM 126", name: "Chem Reactions/Lab"},
	{deptnum: "CHEM 247", name: "Organic Chemistry I"},
	{deptnum: "CHEM 248", name: "Organic Chemistry II"},
	{deptnum: "CHEM 253", name: "Synthesis Lab I"},
	{deptnum: "CHEM 254", name: "Synthesis Lab II"},
	{deptnum: "CHEM 255", name: "Analytical Chem"},
	{deptnum: "CHEM 256", name: "Analytical Lab"},
	{deptnum: "CHEM 357", name: "Physical Lab"},
	{deptnum: "CHEM 371", name: "Physical Chemistry"},
	{deptnum: "CHEM 379", name: "Biochemistry I"},
	{deptnum: "MATH 999", name: "Calculus I"},
	{deptnum: "MATH 128", name: "Calculus II"},
	{deptnum: "PHYS 124", name: "Prin Physics I/Lab"},
	{deptnum: "PHYS 124", name: "Principles Physics I"},
	{deptnum: "PHYS 125", name: "Principles Physics II"},
	{deptnum: "PHYS 125", name: "Prin Physics II/Lab"},
]

let load2 = [
	{deptnum: "CHEM 125", name: "Struct Chem & Equilib Lab"},
	{deptnum: "CHEM 125", name: "Struct Chem & Equilib"},
	{deptnum: "CHEM 126", name: "Chemical Reactions"},
	{deptnum: "CHEM 126", name: "Chem Reactions/Lab"},
	{deptnum: "CHEM 247", name: "Organic Chemistry I"},
	{deptnum: "CHEM 248", name: "Organic Chemistry II"},
	{deptnum: "CHEM 253", name: "Synthesis Lab I"},
	{deptnum: "CHEM 254", name: "Synthesis Lab II"},
	{deptnum: "CHEM 255", name: "Analytical Chem"},
	{deptnum: "CHEM 256", name: "Analytical Lab"},
	{deptnum: "CHEM 357", name: "Physical Lab"},
	{deptnum: "CHEM 371", name: "Physical Chemistry"},
	{deptnum: "CHEM 379", name: "Biochemistry I"},
	{deptnum: "MATH 999", name: "AP Calculus I"},
	{deptnum: "MATH 128", name: "Honors Calculus II"},
	{deptnum: "PHYS 124", name: "Prin Physics I/Lab"},
	{deptnum: "PHYS 124", name: "Principles Physics I"},
	{deptnum: "PHYS 125", name: "Principles Physics II"},
	{deptnum: "PHYS 125", name: "Prin Physics II/Lab"},
]

let load3 = [
	{deptnum: "CH/BI 125", name: "Integrated Chem/Bio I Lab"},
	{deptnum: "CH/BI 125", name: "Integrated Chem/Bio I"},
	{deptnum: "CH/BI 126", name: "Integrate Chem/Bio II Lab"},
	{deptnum: "CH/BI 126", name: "Integrated Chem/Bio II"},
	{deptnum: "CH/BI 127", name: "Integrated Chem/Bio III"},
	{deptnum: "CH/BI 127", name: "Integr Chem/Bio III Lab"},
	{deptnum: "CHEM 247", name: "Organic Chemistry I"},
	{deptnum: "CHEM 248", name: "Organic Chemistry II"},
	{deptnum: "CHEM 253", name: "Synthesis Lab I"},
	{deptnum: "CHEM 254", name: "Synthesis Lab II"},
	{deptnum: "CHEM 255", name: "Analytical Chem"},
	{deptnum: "CHEM 256", name: "Analytical Lab"},
	{deptnum: "CHEM 357", name: "Physical Lab"},
	{deptnum: "CHEM 371", name: "Physical Chemistry"},
	{deptnum: "CHEM 373", name: "Experimental Biochem"},
	{deptnum: "CHEM 379", name: "Biochemistry I"},
	{deptnum: "MATH 999", name: "AP Calculus I and II"},
	{deptnum: "PHYS 124", name: "Prin Physics I/Lab"},
	{deptnum: "PHYS 124", name: "Principles Physics I"},
	{deptnum: "PHYS 125", name: "Principles Physics II"},
	{deptnum: "PHYS 125", name: "Prin Physics II/Lab"},
]

let load4 = [
	{deptnum: "CHEM 121", name: "Gen Chemistry/Lab"},
	{deptnum: "CHEM 121", name: "General Chemistry"},
	{deptnum: "CHEM 123", name: "Atom/Molec Structure"},
	{deptnum: "CHEM 126", name: "Chem Reactions/Lab"},
	{deptnum: "CHEM 126", name: "Chemical Reactions"},
	{deptnum: "CHEM 247", name: "Organic Chemistry I"},
	{deptnum: "CHEM 248", name: "Organic Chemistry II"},
	{deptnum: "CHEM 252", name: "Organometallic Chem"},
	{deptnum: "CHEM 253", name: "Synthesis Lab I"},
	{deptnum: "CHEM 254", name: "Synthesis Lab II"},
	{deptnum: "CHEM 255", name: "Analytical Chem"},
	{deptnum: "CHEM 255", name: "Analytical Chem"},
	{deptnum: "CHEM 256", name: "Analytical Lab"},
	{deptnum: "CHEM 357", name: "Physical Lab"},
	{deptnum: "CHEM 371", name: "Physical Chemistry"},
	{deptnum: "CHEM 379", name: "Biochemistry I"},
	{deptnum: "CHEM 398", name: "IR/"},
	{deptnum: "MATH 120", name: "Calculus I"},
	{deptnum: "MATH 126", name: "Calculus II"},
	{deptnum: "PHYS 124", name: "Principles Physics I"},
	{deptnum: "PHYS 124", name: "Prin Physics I/Lab"},
	{deptnum: "PHYS 125", name: "Prin Physics II/Lab"},
	{deptnum: "PHYS 125", name: "Principles Physics II"},
]

let load5 = [
	{deptnum: "CHEM 125", name: "Struct Chem & Equilib"},
	{deptnum: "CHEM 125", name: "Struct Chem & Equilib Lab"},
	{deptnum: "CHEM 126", name: "Chem Reactions/Lab"},
	{deptnum: "CHEM 126", name: "Chemical Reactions"},
	{deptnum: "CHEM 247", name: "Organic Chemistry I"},
	{deptnum: "CHEM 248", name: "Organic Chemistry II"},
	{deptnum: "CHEM 253", name: "Synthesis Lab I"},
	{deptnum: "CHEM 254", name: "Synthesis Lab II"},
	{deptnum: "CHEM 255", name: "Analytical Chem"},
	{deptnum: "CHEM 256", name: "Analytical Lab"},
	{deptnum: "CHEM 357", name: "Physical Lab"},
	{deptnum: "CHEM 371", name: "Physical Chemistry"},
	{deptnum: "CHEM 378", name: "Instr Analysis Lab"},
	{deptnum: "CHEM 379", name: "Biochemistry I"},
	{deptnum: "CHEM 380", name: "Organic Analys/Theory"},
	{deptnum: "CHEM 380", name: "Organic Analys/Theory Lab"},
	{deptnum: "CHEM 382", name: "Instrumental Analysis"},
	{deptnum: "CHEM 384", name: "Bioanalytic Chemistry"},
	{deptnum: "CHEM 386", name: "Adv Inorganic Chem"},
	{deptnum: "CHEM 388", name: "Adv Organic Chemistry"},
	{deptnum: "CHEM 398", name: "IR/MS Thread Analysis"},
	{deptnum: "MATH 999", name: "AP Calculus I"},
	{deptnum: "MATH 128", name: "Honors Calculus II"},
	{deptnum: "MATH 220", name: "Elem Linear Algebra"},
	{deptnum: "MATH 226", name: "Multivariable Calc"},
	{deptnum: "MATH 230", name: "Differential Equations I"},
	{deptnum: "PHYS 124", name: "Principles Physics I"},
	{deptnum: "PHYS 124", name: "Prin Physics I/Lab"},
	{deptnum: "PHYS 125", name: "Principles Physics II"},
	{deptnum: "PHYS 125", name: "Prin Physics II/Lab"},
]

export default [
	{load: load1, name: 'load1'},
	{load: load2, name: 'load2'},
	{load: load3, name: 'load3'},
	{load: load4, name: 'load4'},
	{load: load5, name: 'load5'},
]
